<?php /*$this->headTitle()->append($this->translate('main-page')); */?>
<div class="wrapper">
    <div class="pad">
        <div class="wrapper"><h2><?php echo  $this->translate('menu-home'); ?></h2></div>
    </div>
    <div class="box pad_bot1 bot">
        <div class="pad marg_top">
            <p>Компания Fasad – успешно развивалась на рынке Украины и хорошо зарекомендовала себя на рынке декоративных отделочных пластиковых материалов, а так же других погонажных изделий из поливинилхлоридных (ПВХ) композиций.</p>
            <p>Наша продукция это объединенный многолетний опыт трёх крупнейших заводов по производству изделий из пластика.</p>
            <p>Продукция, предлагаемая Вам, производится по современным технологиям на новом импортном оборудовании с применением самых передовых научных разработок в системе контроля качества и нанесения декоративного покрытия.</p>
            <p> Все изделия нашего производства изготавливается из ПВХ с применением различных лояльных химических добавок (аддитивов), обеспечивающих пластичность и термостойкость изделий. В своём производстве, мы используем  исключительно первичное сырьё, и только лучшие компоненты ведущих мировых производителей.</p>
            <p>Мы готовы предложить разнообразие размеров и ассортимент различных фассадных декоров, которые смогут удовлетворить вкус даже самого требовательного покупателя. Вся продукция сертифицирована соответствует нормам и требованиям государственных стандартов.</p>
            <!--<ul class="list1 pad_bot4">
                <li><a href="index.html">Home page</a></li>
                <li><a href="About.html">About us</a></li>
                <li><a href="Projects.html">Projects</a></li>
                <li><a href="Contacts.html">Contact us</a></li>
                <li><a href="Sitemap.html">Site map</a></li>
            </ul>
            <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati.</p>-->
        </div>
    </div>
</div>