<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/reset.css" type="text/css" media="all">
    <link rel="stylesheet" href="css/layout.css" type="text/css" media="all">
    <link rel="stylesheet" href="css/style.css" type="text/css" media="all">
    <script type="text/javascript" src="js/jquery-1.4.2.js" ></script>
    <script type="text/javascript" src="js/cufon-yui.js"></script>
    <script type="text/javascript" src="js/cufon-replace.js"></script>
    <script type="text/javascript" src="js/Copse_400.font.js"></script>
    <script type="text/javascript" src="js/jquery.nivo.slider.pack.js"></script>
    <script type="text/javascript" src="js/imagepreloader.js"></script>
    <script type="text/javascript">
        preloadImages([
            'images/menu1_active.gif',
            'images/menu2_active.gif',
            'images/menu3_active.gif',
            'images/menu4_active.gif',
            'images/marker_right_active.jpg',
            'images/marker_left_active.jpg',
            'images/menu5_active.gif']);
    </script>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="http://info.template-help.com/files/ie6_warning/ie6_script_other.js"></script>
    <script type="text/javascript" src="js/html5.js"></script>
    <![endif]-->
</head>
<body id="page1">
<div class="body1">
    <div class="body2">
        <div class="main">
            <!-- header -->
            <header>
                <div class="wrapper">
                    <h1><a href="index.html" id="logo">bs-code</a></h1>
                    <div class="right">
                       <!-- <nav>
                            <ul id="top_nav">
                                <li><a href="#">User Area</a></li>
                                <li><a href="#">Sitemap</a></li>
                            </ul>
                            <form id="search" method="post">
                                <div>
                                    <input type="submit" class="submit" value="">
                                    <input type="text" class="input">
                                </div>
                            </form>
                        </nav>-->
                    </div>
                </div>
                <nav id="menu">
                    <ul>
                        <li id="active" class="nav1"><a href="/">Home</a></li>
                        <li class="nav2"><a href="/about">About</a></li>
                        <li class="nav3"><a href="/services">Services</a></li>
                        <li class="nav4"><a href="/products">Products</a></li>
                        <li class="nav5"><a href="/contact">Contact</a></li>
                    </ul>
                </nav>
            </header><!--<div class="ic">More Website Templates at TemplateMonster.com!</div>-->
        </div>
    </div>
</div>
<div class="body3">
    <div class="body4">
        <div class="main">
            <div class="slogan">
                <div id="slider">
                    <img src="images/text1.jpg" alt="">
                    <img src="images/text2.jpg" alt="">
                    <img src="images/text3.jpg" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- / header -->
<!-- content -->
<?php echo $this->layout()->content; ?>
<!-- / content -->
<!-- footer -->
<div class="body8">
    <div class="body9">
        <div class="main">
            <footer>
                <div class="col_1">
                    <h3>Social Networks</h3>
                    <ul class="list3">
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Flickr</a></li>
                        <li><a href="#">Blogger</a></li>
                    </ul>
                </div>
                <div class="col_2 pad_left1">
                    <h3>Quick Solutions</h3>
                    <div class="wrapper">
                        <ul class="list3 col_1">
                            <li><a href="#">Management Consulting</a></li>
                            <li><a href="#">Policy and Regulatory</a></li>
                            <li><a href="#">Market Assessment</a></li>
                            <li><a href="#">Program Management</a></li>
                        </ul>
                        <ul class="list3 col_1 pad_left1">
                            <li><a href="#">Regulatory Support</a></li>
                            <li><a href="#">Risk Assessment</a></li>
                            <li><a href="#">Change Management</a></li>
                            <li><a href="#">Info Technology</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col_3">
                    <a href="index.html" id="footer_logo">First</a>
                    <p class="center"><a rel="nofollow" href="http://www.templatemonster.com/" target="_blank">Website template</a><br>
                        designed by TemplateMonster.com</p>
                    <p class="center">
                        <a href="http://www.templates.com/product/3d-models/" target="_blank">3D Models</a><br>
                        provided by Templates.com</p>
                </div>
            </footer>
        </div>
        <!-- / footer -->
    </div>
</div>
<script type="text/javascript">
    Cufon.now();
    $(document).ready(function(){
        $('#menu ul li').each(function(index) {
            $(this).addClass("nav"+(index+1));
        });
    });
</script>
<script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider({
            effect:'sliceDown', //Specify sets like: 'fold,fade,sliceDown, sliceDownLeft, sliceUp, sliceUpLeft, sliceUpDown, sliceUpDownLeft'
            slices:20,
            animSpeed:300,
            pauseTime:9999999999,
            startSlide:0, //Set starting Slide (0 index)
            directionNav:true, //Next & Prev
            directionNavHide:false, //Only show on hover
            controlNav:false, //1,2,3...
            controlNavThumbs:false, //Use thumbnails for Control Nav
            controlNavThumbsFromRel:false, //Use image rel for thumbs
            controlNavThumbsSearch: '.jpg', //Replace this with...
            controlNavThumbsReplace: '_thumb.jpg', //...this in thumb Image src
            keyboardNav:true, //Use left & right arrows
            pauseOnHover:true, //Stop animation while hovering
            manualAdvance:false, //Force manual transitions
            captionOpacity:1, //Universal caption opacity
            beforeChange: function(){},
            afterChange: function(){},
            slideshowEnd: function(){} //Triggers after all slides have been shown
        });
    });
</script>
</body>
</html>