<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/reset.css" type="text/css" media="all">
    <link rel="stylesheet" href="css/layout.css" type="text/css" media="all">
    <link rel="stylesheet" href="css/style.css" type="text/css" media="all">
    <link rel="stylesheet" href="themes/default/default.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="themes/pascal/pascal.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="themes/orman/orman.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="css/nivo-slider.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="css/menu_core.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="css/menu_redBar.css" type="text/css" media="screen" />
    <script type="text/javascript" src="js/jquery-1.7.1.min.js" ></script>
    <script type="text/javascript" src="js/cufon-yui.js"></script>
    <script type="text/javascript" src="js/cufon-replace.js"></script>
    <script type="text/javascript" src="js/Myriad_Pro_400.font.js"></script>
    <script type="text/javascript" src="js/Myriad_Pro_700.font.js"></script>
    <script type="text/javascript" src="js/Myriad_Pro_600.font.js"></script>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="http://info.template-help.com/files/ie6_warning/ie6_script_other.js"></script>
    <script type="text/javascript" src="js/html5.js"></script>
    <![endif]-->
    <script type="text/javascript" src="js/jquery.nivo.slider.pack.js"></script>
    <script type="text/javascript" src="js/api.js"></script>
</head>
<body id="page1">
<div class="main">
    <!-- header -->
    <header>
        <div class="wrapper">
            <h1><a href="index.html" id="logo">Smart Biz</a></h1>
            <div id="locale">
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'locale', 'action' => 'index', 'locale' => 'ro_MD'), 'default', true); ?>">
                    <img src="/images/locale/ro_MD.png" />
                </a>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'locale', 'action' => 'index', 'locale' => 'ru_RU'), 'default', true); ?>">
                    <img src="/images/locale/ru_RU.png" />
                </a>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'locale', 'action' => 'index', 'locale' => 'en_US'), 'default', true); ?>">
                    <img src="/images/locale/en_US.png" />
                </a>

            </div>
        </div>
        <div class="wrapper">
            <!--            <div class="text">
                <span class="text1">Effective<span>business solutions</span></span>
                <a href="#" class="button">read more</a>
            </div>-->
            <div class="slider-wrapper theme-default">
                <div class="ribbon"></div>
                <div id="slider" class="nivoSlider">
                    <img src="images/Untitled.jpg" alt="" />
                    <img src="images/Untitled1.jpg" alt="" />
                </div>
            </div>
        </div>
<!--        <nav>
            <ul id="menu">
                <li class="alpha" id="menu_active"><a href="index.html"><span><span>Home</span></span></a></li>
                <li><a href="About.html"><span><span>About</span></span> </a></li>
                <li><a href="Projects.html"><span><span>Projects</span></span></a></li>
                <li><a href="Contacts.html"><span><span>Contacts</span></span></a></li>
                <li class="omega"><a href="Sitemap.html"><span><span>Sitemap</span></span></a></li>
            </ul>
        </nav>-->
        <!-- Menu structure example -->
        <div id="myMenu" class="nfPure nfMain" style="width:920px;">

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_home">Home</span></a></h2></div>

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_facade">Facade</span></a></h2>
                <div class="nfSubC"><ul class="nfSubS">
                    <li class="nfItem"><a class="nfLink" href="#">Siding</a></li>
                    <li class="nfItem"><a class="nfLink" href="#">Sofit</a></li>
                    <li class="nfItem"><a class="nfLink" href="#">Siding color chooser</a></li>
                </div>
            </div>


            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_walls">Walls &amp; Roofs</span></a></h2>
                <div class="nfSubC"><ul class="nfSubS">
                    <li class="nfItem"><a class="nfLink" href="#">Accessory</a></li>
                    <li class="nfItem"><a class="nfLink" href="#">PVC wall panels</a></li>
                </ul>
                </div>
            </div>

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_windows">Windows</span></a></h2>
                <div class="nfSubC"><ul class="nfSubS">
                    <li class="nfItem"><a class="nfLink" href="#">PVC Window sills</a></li>
                </ul>
                </div>
            </div>

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_pipes">PVC pipes</span></a></h2>
                <div class="nfSubC"><ul class="nfSubS">
                    <li class="nfItem"><a class="nfLink" href="#">Accessory</a></li>
                </ul>
                </div>
            </div>

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_prices">Prices</span></a></h2></div>

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_company">Company</span></a></h2>
                <div class="nfSubC"><ul class="nfSubS">
                    <li class="nfItem"><a class="nfLink" href="#">About Company</a></li>
                    <li class="nfItem"><a class="nfLink" href="#">Market outlet</a></li>
                </ul>
                </div>
            </div>

            <div class="nfItem"><h2><a class="nfLink" href="#"><span id="gn_phones">Contacts</span></a></h2></div>

        </div>
    </header><div class="ic">More Website Templates at TemplateMonster.com!</div>
    <!-- / header -->
    <!-- content -->
    <section id="content">
        <div class="wrapper">
            <div class="wrapper">
                <ul class="banners">
                    <li>
                        <a href="#"><img src="images/page1_img1.jpg" alt=""></a>
                        <div class="pad">
                            <p class="font1">Company History</p>
                            <p>Lorem ipsum doloamet consect etuer adipiscing.</p>
                            <a href="#" class="marker"></a>
                        </div>
                    </li>
                    <li>
                        <a href="#"><img src="images/page1_img2.jpg" alt=""></a>
                        <div class="pad">
                            <p class="font1">Our Capabilities</p>
                            <p>Sed ut perspiciatis unde omnis iste naturror voluptatem.</p>
                            <a href="#" class="marker"></a>
                        </div>
                    </li>
                    <li>
                        <a href="#"><img src="images/page1_img3.jpg" alt=""></a>
                        <div class="pad">
                            <p class="font1">Where We Deliver</p>
                            <p>Nam libero tempore cum soluta nobis est eligendi optio.</p>
                            <a href="#" class="marker"></a>
                        </div>
                    </li>
                    <li>
                        <a href="#"><img src="images/page1_img4.jpg" alt=""></a>
                        <div class="pad">
                            <p class="font1">Operations Consulting</p>
                            <p>Temporibus autem quibusdam et aut officiis.</p>
                            <a href="#" class="marker"></a>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="wrapper">
                <div class="box bot pad_bot2">
                    <div class="pad">
                        <article class="col1">
                            <h2>Take the best business deal</h2>
                            <strong>Smart Biz Template</strong> is one of <a rel="nofollow" href="http://www.templatemonster.com/website-templates.php" target="_blank">free website templates</a> created by Templates.com team. This website template is optimized for 1024X768 screen resolution. It is also XHTML &amp; CSS valid.
                            <div class="wrapper">
                                <figure class="left marg_right1 marg_top2"><img src="images/page1_img5.jpg" alt=""></figure>
                                <p class="marg_top">This <a href="http://blog.templatemonster.com/2011/01/24/free-business-website-template-efficient-choice/" target="_blank">Free Business Website Template</a> goes with two packages – with PSD source files and without them. PSD source files are available for free for the registered members of Templates.com. The basic package (without PSD is available for anyone without registration).</p>
                            </div>
                            <p>This website template has several pages: <a href="index.html">Home</a>, <a href="About.html">About</a>, <a href="Projects.html">Projects</a>, <a href="Contacts.html">Contacts</a> (note that contact us form – doesn’t work), <a href="Sitemap.html">Sitemap</a>.</p>
                            <div class="wrapper line1">
                                <ul class="list1 cols">
                                    <li><a href="#">At vero eos et accusamus iusto</a></li>
                                    <li><a href="#">Odio dignissimos ducimus</a></li>
                                    <li><a href="#">Blanditiis praesentium voluptatum</a></li>
                                    <li><a href="#">Deleniti atque corrupti quos dolores</a></li>
                                </ul>
                                <ul class="list1 cols pad_left2">
                                    <li><a href="#">Sint occaecati cuditate nongd</a></li>
                                    <li><a href="#">Provident similque suxpin culpa qui</a></li>
                                    <li><a href="#">Officia deserunt mollitia animidt</a></li>
                                    <li><a href="#">Etharum quidem rerum facili</a></li>
                                </ul>
                            </div>
                        </article>
                        <article class="col2 pad_left1">
                            <h2>Latest projects</h2>
                            <div class="wrapper">
                                <div class="wrapper pad_bot1">
                                    <figure class="left marg_right1"><a href="#"><img src="images/page1_img6.jpg" alt=""></a></figure>
                                    <p>Sed peraspiciatis unde omnis iste natus eraror sit voluptatem accusantium doloremque.</p>
                                    <a href="#" class="marker"></a>
                                </div>
                                <div class="wrapper pad_bot1">
                                    <figure class="left marg_right1"><a href="#"><img src="images/page1_img7.jpg" alt=""></a></figure>
                                    <p>Laudantiuam totam aperiam, eaque ipsa quaae ab illo inventore veritatais quasi.</p>
                                    <a href="#" class="marker"></a>
                                </div>
                                <div class="wrapper">
                                    <figure class="left marg_right1"><a href="#"><img src="images/page1_img8.jpg" alt=""></a></figure>
                                    <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit sed.</p>
                                    <a href="#" class="marker"></a>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- / content -->
    <!-- footer -->
    <footer>
        <a rel="nofollow" href="http://www.templatemonster.com/" target="_blank">Website template</a> designed by TemplateMonster.com<br>
        <a href="http://www.templates.com/product/3d-models/" target="_blank">3D Models</a> provided by Templates.com
    </footer>
    <!-- / footer -->
</div>
<script type="text/javascript"> Cufon.now(); </script>
<script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
</script>

<!--Create a new menu object and activate it (place this script after the structure or attach to an onload type event)-->
<script type="text/javascript">


    //Menu configuration properties (hide and show timers in Milliseconds)
    var config = {showTimerMS:250,hideTimerMS:250,stickyHover:true};

    //Pass the menu object construcor an ID or object representing the root node of your structure
    var myMenu = new NF.widget.menu("myMenu", config);

    //set the default delay timer for the menus playerSynchronizer animations
    NF.anim.playerSynchronizer.delay = 15;


    /*~~~~~~~~ Hover Effect - Level 1~~~~~~~~~~~~~*/
    var hovClip = new NF.anim.clip({backgroundColor:{start:"#000000",end:"#990101"}},{frames:5,hook:"NFplayOnLinkHoverShow"});
    myMenu.addReplicator(new NF.replicator("transition",{master:hovClip,widgetClass:"nfItem",targetClass:"nfLink",widgetLevel:"level==1"}));

    hovClip = new NF.anim.clip({backgroundColor:{start:"#990101",end:"#000000"}},{frames:40,hook:"NFplayOnLinkHoverHide"});
    myMenu.addReplicator(new NF.replicator("transition",{master:hovClip,widgetClass:"nfItem",targetClass:"nfLink",widgetLevel:"level==1"}));


    /*~~~~~~~~ Hover Effect - Level 2~~~~~~~~~~~~~*/
    var hovClip = new NF.anim.clip({backgroundColor:{start:"#222222",end:"#990101"}},{frames:5,reset:true,hook:"NFplayOnLinkHoverShow"});
    myMenu.addReplicator(new NF.replicator("transition",{master:hovClip,widgetClass:"nfItem",targetClass:"nfLink",widgetLevel:"level==2"}));

    hovClip = new NF.anim.clip({backgroundColor:{start:"#990101",end:"#222222"}},{frames:40,reset:true,hook:"NFplayOnLinkHoverHide"});
    myMenu.addReplicator(new NF.replicator("transition",{master:hovClip,widgetClass:"nfItem",targetClass:"nfLink",excludeClass:"nfParentLink",widgetLevel:"level==2"}));


    /*~~~~~~~~ Show Subs Effect - Lev 1 ~~~~~~~~~~~~~*/
    var clip = new NF.anim.clip({opacity:{start:0, end:1}}, {frames:10,reset:true,hook:"NFplayOnSubShow"});
    var subAnim_Show_Replicator = new NF.replicator("transition", {master:clip,widgetClass:"nfSubC",widgetLevel:'level==1'});
    myMenu.addReplicator(subAnim_Show_Replicator);


    /*~~~~~~~~ Hide Subs Effect - Lev 1 ~~~~~~~~~~~~~*/
    clip = new NF.anim.clip({opacity:{start:1, end:0}}, {frames:10,reset:true,hook:"NFplayOnSubHide"});
    var subAnim_Hide_Replicator = new NF.replicator("transition", {master:clip,widgetClass:"nfSubC",widgetLevel:'level==1'});
    myMenu.addReplicator(subAnim_Hide_Replicator);


    /*~~~~~~~~ Show Subs Effect - Lev 2+ ~~~~~~~~~~~~~*/
    var clip1 = new NF.anim.clip({opacity:{start:0, end:1}}, {frames:10,reset:true,hook:"NFplayOnSubShow"});
    var clip2 = new NF.anim.clip({clip:{start:{value:'0% 0% 0% 0%', refNode:"self"}, end:{value:'0% 100% 100% 0%', refNode:"self"}}}, {frames:12,reset:true,hook:"NFplayOnSubShow"});
    var timeline = new NF.anim.timeline(clip1,'NFplayOnSubShow');
    timeline.addTrack(clip2);
    var subAnim_Show_Replicator = new NF.replicator("transition", {master:timeline,widgetClass:"nfSubC",widgetLevel:'level>1'});
    myMenu.addReplicator(subAnim_Show_Replicator);


    /*~~~~~~~~ Hide Subs Effect - Lev 2+ ~~~~~~~~~~~~~*/
    clip1 = new NF.anim.clip({opacity:{start:1, end:0}}, {frames:10,reset:true,hook:"NFplayOnSubHide"});
    clip2 = new NF.anim.clip({clip:{start:{value:'0% 100% 100% 0%', refNode:"self"}, end:{value:'0% 0% 0% 0%', refNode:"self"}}}, {frames:12,reset:true,hook:"NFplayOnSubHide"});
    timeline = new NF.anim.timeline(clip1,'NFplayOnSubHide');
    timeline.addTrack(clip2);
    var subAnim_Hide_Replicator = new NF.replicator("transition", {master:timeline,widgetClass:"nfSubC",widgetLevel:'level>1'});
    myMenu.addReplicator(subAnim_Hide_Replicator);


    //Activate the menu
    myMenu.activate();




</script>
</body>
</html>