<!DOCTYPE html>
<html lang="en">
<head>
    <title>BS code</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/reset.css" type="text/css" media="all">
    <link rel="stylesheet" href="css/layout.css" type="text/css" media="all">
    <link rel="stylesheet" href="css/style.css" type="text/css" media="all">
    <script type="text/javascript" src="js/jquery-1.4.2.js" ></script>
    <script type="text/javascript" src="js/cufon-yui.js"></script>
    <script type="text/javascript" src="js/cufon-replace.js"></script>
    <script type="text/javascript" src="js/Copse_400.font.js"></script>
    <script type="text/javascript" src="js/imagepreloader.js"></script>
    <script type="text/javascript">
        preloadImages([
            'images/menu1_active.gif',
            'images/menu2_active.gif',
            'images/menu3_active.gif',
            'images/menu4_active.gif',
            'images/menu5_active.gif']);
    </script>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="http://info.template-help.com/files/ie6_warning/ie6_script_other.js"></script>
    <script type="text/javascript" src="js/html5.js"></script>
    <![endif]-->
</head>
<body id="page3">
<div class="body1">
    <div class="body2">
        <div class="main">
            <!-- header -->
            <header>
                <div class="wrapper">
                    <h1><a href="index.html" id="logo">bs-code</a></h1>
                    <div class="right">
                       <!-- <nav>
                            <ul id="top_nav">
                                <li><a href="#">User Area</a></li>
                                <li><a href="#">Sitemap</a></li>
                            </ul>
                            <form id="search" method="post">
                                <div>
                                    <input type="submit" class="submit" value="">
                                    <input type="text" class="input">
                                </div>
                            </form>
                        </nav>-->
                    </div>
                </div>
<!--                <nav id="menu">
                    <?php /*echo  $this->navigation()->menu(); */?>
                </nav>-->
                <nav id="menu">
                    <ul>
                        <li class="nav1"><a href="/">Home</a></li>
                        <li class="nav2"><a href="/about">About</a></li>
                        <li class="nav3"><a href="/services">Services</a></li>
                        <li class="nav4"><a href="/products">Products</a></li>
                        <li class="nav5"><a href="/contact">Contact</a></li>
                    </ul>
                </nav>
            </header><!--<div class="ic">More Website Templates at TemplateMonster.com!</div>-->
        </div>
    </div>
</div>
<!-- / header -->
<!-- content -->
<?php echo $this->layout()->content; ?>
<!-- / content -->
<!-- footer -->
<div class="body8">
    <div class="body9">
        <div class="main">
            <footer>
                <div class="col_1">
                    <h3>Social Networks</h3>
                    <ul class="list3">
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Flickr</a></li>
                        <li><a href="#">Blogger</a></li>
                    </ul>
                </div>
                <div class="col_2 pad_left1">
                    <h3>Quick Solutions</h3>
                    <div class="wrapper">
                        <ul class="list3 col_1">
                            <li><a href="#">Management Consulting</a></li>
                            <li><a href="#">Policy and Regulatory</a></li>
                            <li><a href="#">Market Assessment</a></li>
                            <li><a href="#">Program Management</a></li>
                        </ul>
                        <ul class="list3 col_1 pad_left1">
                            <li><a href="#">Regulatory Support</a></li>
                            <li><a href="#">Risk Assessment</a></li>
                            <li><a href="#">Change Management</a></li>
                            <li><a href="#">Info Technology</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col_3">
                    <a href="index.html" id="footer_logo">First</a>
                    <p class="center"><a rel="nofollow" href="http://www.templatemonster.com/" target="_blank">Website template</a><br>designed by TemplateMonster.com</p>
                    <p class="center"><a href="http://www.templates.com/product/3d-models/" target="_blank">3D Models</a><br>provided by Templates.com</p>
                </div>
            </footer>
        </div>
        <!-- / footer -->
    </div>
</div>
<script type="text/javascript">
    Cufon.now();
    $(document).ready(function(){
        var fullPathname = window.location.pathname;
        var arrayPathname = fullPathname.split("/");
        //console.log(arrayPathname[1]);
        $('#menu ul li').each(function(index) {
            $(this).addClass("nav"+(index+1));
            var fulllink = $(this).find('a').attr('href');
            var arraylink = fulllink.split("/");
            //console.log(arraylink[1]);
            if(arrayPathname[1] == arraylink[1]){
                $(this).attr('id', 'active');
            }
        });
        //console.log(res);
    });
</script>
</body>
</html>